// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFCdWUvAcpHFTE2jeo41KmKtVZMlaxqUg',
    appId: '1:719098947980:web:9fe708c803a8a2a0c30ea9',
    messagingSenderId: '719098947980',
    projectId: 'liuchatapp-92613',
    authDomain: 'liuchatapp-92613.firebaseapp.com',
    storageBucket: 'liuchatapp-92613.appspot.com',
    measurementId: 'G-5W1LTJGQVB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDvcLg6CeI6d4jZPBPdqJUi5f2C-ZEXwc',
    appId: '1:719098947980:android:6ba6e9383e3be842c30ea9',
    messagingSenderId: '719098947980',
    projectId: 'liuchatapp-92613',
    storageBucket: 'liuchatapp-92613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPfE_fR7CGa0dtYGLFAjazAbIxeNmtKng',
    appId: '1:719098947980:ios:b6bbe43917cd1759c30ea9',
    messagingSenderId: '719098947980',
    projectId: 'liuchatapp-92613',
    storageBucket: 'liuchatapp-92613.appspot.com',
    iosBundleId: 'com.example.liuchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPfE_fR7CGa0dtYGLFAjazAbIxeNmtKng',
    appId: '1:719098947980:ios:b6bbe43917cd1759c30ea9',
    messagingSenderId: '719098947980',
    projectId: 'liuchatapp-92613',
    storageBucket: 'liuchatapp-92613.appspot.com',
    iosBundleId: 'com.example.liuchatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFCdWUvAcpHFTE2jeo41KmKtVZMlaxqUg',
    appId: '1:719098947980:web:b054749dd1779fccc30ea9',
    messagingSenderId: '719098947980',
    projectId: 'liuchatapp-92613',
    authDomain: 'liuchatapp-92613.firebaseapp.com',
    storageBucket: 'liuchatapp-92613.appspot.com',
    measurementId: 'G-L957GEJFKQ',
  );

}